version: "3"

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/home/avito/web
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017

